### ISSUE TITLE
TypeError: req.handle.writev is not a function

### ISSUE THREAD

**Issue by mrhaxic** [ovh-ux/ovh-manager-dedicated#476]
While running `make dev` I got the below error

internal/stream_base_commons.js:59
  var err = req.handle.writev(req, chunks, allBuffers);
                       ^

TypeError: req.handle.writev is not a function
    at writevGeneric (internal/stream_base_commons.js:59:24)
    at Socket._writeGeneric (net.js:758:5)
    at Socket._writev (net.js:767:8)
    at doWrite (_stream_writable.js:408:12)
    at clearBuffer (_stream_writable.js:517:5)
    at Socket.Writable.uncork (_stream_writable.js:314:7)
    at connectionCorkNT (_http_outgoing.js:646:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Stopping Express server

**Comment by antleblanc** [comment]
Hi @mrhaxic,

Can you tell me which version of Node.js you are using?

```sh
$ node --version
```

Thanks.

**Comment by antleblanc** [comment]
@mrhaxic I can't reproduce.

```sh
$ node --version && npm --version && yarn --version && grunt --version
v10.6.0
6.1.0
1.7.0
grunt-cli v1.2.0
grunt v0.4.5
```

Could you give me your the versions of `yarn`, `npm` & `grunt`?
And what is your OS environment?

**Comment by mrhaxic** [comment]
Sure here you are

v10.6.0
6.2.0
1.7.0
grunt-cli v1.2.0

I used macOS, hope this helps you to reproduce the issue.

**Comment by mrhaxic** [comment]
Yes, now it is working fine. Thanks a lot 👍
